name: Deploy to cPanel

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Prepare deployment files
        run: |
          # Créer un dossier temporaire pour le déploiement
          mkdir -p deploy_temp

          # Copier le contenu de dist/ (frontend build)
          cp -r dist/* deploy_temp/

          # Copier les fichiers backend et config
          cp -r api deploy_temp/
          cp -r database deploy_temp/
          cp .htaccess deploy_temp/

          # Créer les dossiers nécessaires
          mkdir -p deploy_temp/api/uploads/documents
          mkdir -p deploy_temp/api/logs

          # Liste des fichiers à déployer
          ls -la deploy_temp/

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./deploy_temp/
          server-dir: ./public_html/
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/src/**
            **/.env
            **/package*.json
            **/tsconfig*.json
            **/vite.config.ts
            **/postcss.config.js
            **/tailwind.config.js

      - name: Notification
        if: success()
        run: |
          echo "✅ Déploiement réussi sur https://coffice.dz"
          echo "📦 Version déployée: $(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')"

      - name: Notification échec
        if: failure()
        run: |
          echo "❌ Échec du déploiement"
          echo "Vérifiez les logs ci-dessus pour plus de détails"
