name: Deploy to cPanel
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger cPanel Update and Deploy
        run: |
          # 1. Mise à jour (Pull)
          curl -H "Authorization: cpanel ${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_API_TOKEN }}" \
          "${{ secrets.CPANEL_URL }}/execute/VersionControl/update?repository_root=/home/cofficed/repositories/coffice"
          
          # 2. Déploiement (Exécution du .cpanel.yml)
          curl -H "Authorization: cpanel ${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_API_TOKEN }}" \
          "${{ secrets.CPANEL_URL }}/execute/VersionControl/deploy?repository_root=/home/cofficed/repositories/coffice"
